name: doctor_service_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.7.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 0.13.5
  provider: ^6.0.5
  sidebarx: ^0.14.0
  table_calendar: ^3.0.8
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2
  flutter_treeview: 1.0.7+1
  syncfusion_flutter_calendar: ^20.4.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true